# Generated by Django 3.1.7 on 2021-03-12 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
