# Generated by Django 3.1.7 on 2021-03-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_delete_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('reserved_date', models.DateTimeField()),
                ('finished_date', models.DateTimeField()),
                ('wish_user_list', models.IntegerField()),
                ('status', models.IntegerField()),
                ('target_demand', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('host_id', models.IntegerField()),
                ('question_id', models.IntegerField()),
                ('live_id', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
