# Generated by Django 3.1.7 on 2021-03-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0005_auto_20210312_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='finished_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='reserved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
