# Generated by Django 3.1.7 on 2021-03-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0007_auto_20210312_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
