# Generated by Django 3.1.7 on 2021-03-12 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('holes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('questions', models.TextField(null=True)),
                ('hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='holes.hole')),
            ],
        ),
    ]
