# Generated by Django 3.1.7 on 2021-03-12 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0009_auto_20210312_2205'),
        ('users', '0002_auto_20210312_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='session.session'),
        ),
    ]
