# Generated by Django 3.1.7 on 2021-03-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='social_account',
            field=models.CharField(blank=True, choices=[('instagram', 'Instagram')], max_length=50, null=True),
        ),
    ]
