# Generated by Django 3.1.7 on 2021-03-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210323_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
