# Generated by Django 3.1.7 on 2021-03-22 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holes', '0007_auto_20210322_1639'),
        ('chat_messages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='author',
            new_name='sender',
        ),
        migrations.AddField(
            model_name='message',
            name='converstaion',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='holes.livehole'),
        ),
    ]
