# Generated by Django 3.1.7 on 2021-03-22 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holes', '0007_auto_20210322_1639'),
        ('chat_messages', '0002_auto_20210322_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='converstaion',
        ),
        migrations.AlterField(
            model_name='message',
            name='livehole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='holes.livehole'),
        ),
    ]
