# Generated by Django 3.1.7 on 2021-04-08 03:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0003_auto_20210322_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='start_at',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
