# Generated by Django 3.1.7 on 2021-04-10 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0004_message_start_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='start_at',
        ),
    ]
