# Generated by Django 3.1.7 on 2021-03-23 08:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hole_reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='guests',
            field=models.ManyToManyField(blank=True, default='', related_name='hole_reservations', to=settings.AUTH_USER_MODEL),
        ),
    ]
