# Generated by Django 3.1.7 on 2021-03-25 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hole_reservations', '0002_auto_20210323_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='reserve_start_date',
            new_name='reserve_date',
        ),
    ]
