# Generated by Django 3.1.7 on 2021-03-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hole_reservations', '0004_auto_20210325_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='current_demand',
            field=models.IntegerField(default=0),
        ),
    ]
