# Generated by Django 3.1.7 on 2021-03-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hole_reservations', '0005_reservation_current_demand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('host_confirmed', 'Host Confirmed'), ('canceled', 'Canceled')], default='pending', max_length=30),
        ),
    ]
