# Generated by Django 3.1.7 on 2021-03-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hole_reservations', '0006_auto_20210328_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('CONFIRMED', 'CONFIRMED'), ('HOST_CONFIRMED', 'HOST_CONFIRMED'), ('CANCELED', 'CANCELED')], default='PENDING', max_length=30),
        ),
    ]
