# Generated by Django 3.1.7 on 2021-03-31 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holes', '0015_auto_20210329_1126'),
        ('hole_reservations', '0007_auto_20210328_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='hole',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='hole_reservations', to='holes.hole'),
        ),
    ]
