# Generated by Django 3.1.7 on 2021-03-12 15:14

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('holes', '0002_hole_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveHole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livehole_user_ids', django_mysql.models.ListTextField(models.IntegerField(), size=30)),
                ('hole', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='livehole', to='holes.hole')),
            ],
        ),
    ]
