# Generated by Django 3.1.7 on 2021-03-13 07:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('holes', '0002_auto_20210313_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livehole',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='liveholes', to=settings.AUTH_USER_MODEL),
        ),
    ]
