# Generated by Django 3.1.7 on 2021-03-17 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('holes', '0002_auto_20210314_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='livehole',
            name='audience_list',
            field=django_mysql.models.ListTextField(models.IntegerField(), null=True, size=30),
        ),
        migrations.AddField(
            model_name='livehole',
            name='host_uid',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='livehole',
            name='room_number',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='livehole',
            name='hole',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='liveholes', to='holes.hole'),
        ),
        migrations.AlterField(
            model_name='livehole',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='liveholes_participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
