# Generated by Django 3.1.7 on 2021-03-22 06:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('holes', '0005_auto_20210317_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='livehole',
            name='participants',
            field=models.ManyToManyField(blank=True, default='', related_name='liveholes_participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
