# Generated by Django 3.1.7 on 2021-03-22 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holes', '0006_livehole_participants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livehole',
            old_name='audience_list',
            new_name='audience_uids',
        ),
        migrations.RenameField(
            model_name='livehole',
            old_name='room_number',
            new_name='hole_number',
        ),
    ]
