# Generated by Django 3.1.7 on 2021-03-23 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('holes', '0007_auto_20210322_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livehole',
            name='hole_number',
        ),
        migrations.RemoveField(
            model_name='livehole',
            name='participants',
        ),
        migrations.AlterField(
            model_name='livehole',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('livehole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='holes.livehole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
