# Generated by Django 3.1.7 on 2021-03-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holes', '0008_auto_20210323_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='leaved',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
