# Generated by Django 3.1.7 on 2021-03-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holes', '0010_auto_20210324_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livehole',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
