# Generated by Django 3.1.7 on 2021-03-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holes', '0011_auto_20210324_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='is_voice',
            field=models.BooleanField(default=False),
        ),
    ]
