# Generated by Django 3.1.7 on 2021-03-29 02:26

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('holes', '0014_auto_20210329_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livehole',
            name='audience_uids',
            field=django_mysql.models.ListTextField(models.BigIntegerField(), blank=True, default='', size=30),
        ),
    ]
