# Generated by Django 3.1.7 on 2021-04-01 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holes', '0015_auto_20210329_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hole',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='hole',
            name='subtitle',
        ),
    ]
